# Generated by Django 3.2.5 on 2022-02-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_delete_usecase_userstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='use_case',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
