# Generated by Django 3.2.5 on 2021-12-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Concept', 'Concept'), ('Pre Alpha', 'Prealpha'), ('Alpha', 'Alpha'), ('Beta', 'Beta'), ('Release Candidate', 'Review'), ('Live', 'Live')], default='Concept', max_length=24),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='status',
            field=models.CharField(choices=[('Not Supported', 'Na'), ('Queued', 'Queued'), ('Review', 'Review'), ('Live', 'Live')], max_length=24),
        ),
    ]
