# Generated by Django 3.2.5 on 2021-12-28 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20211228_0202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UseCase_UserStory',
        ),
    ]
