# Generated by Django 3.2.5 on 2022-01-08 00:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_delete_usecase_userstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes',
            field=ckeditor.fields.RichTextField(default='enter notes'),
            preserve_default=False,
        ),
    ]
