# Generated by Django 3.2.5 on 2022-01-08 00:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_client_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
