# Generated by Django 3.2.5 on 2022-01-08 02:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_client_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
