# Generated by Django 3.2.5 on 2022-01-12 23:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_client_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=512),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=512),
        ),
    ]
